receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  file:
    path: /var/log/example/output.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [file]
