global:
  scrape_interval: 15s
  external_labels:
    monitor: kotel_monitor

scrape_configs:
  - job_name: kotel_example
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'krakend_front:9090'
        - 'krakend_middle:9090'
        - 'krakend_back:9090'
        labels:
          app: kotel_example
