volumes:
  vol_local_tempo:
  vol_local_grafana:
  vol_local_prometheus:
services:
  tracelogger:
    image: otel/opentelemetry-collector:0.94.0
    ports:
      - "24317:4317"
      - "25679:55679"
    volumes:
      - "./conf.local/tracelogger/config.yaml:/etc/otelcol/config.yaml"
      - "./tmp:/var/log/example"
    user: "1000"
  loki:
    image: grafana/loki:latest
    domainname: loki
    healthcheck:
      test: [CMD, wget, --spicer, -S, http://localhost:3100/ready]
    ports:
      - "53100:3100"
  tempo:
    image: grafana/tempo:latest
    domainname: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "./conf.local/tempo/tempo.yaml:/etc/tempo.yaml"
      - "vol_local_tempo:/tmp/tempo"
    ports:
      - "53200:3200"     # tempo
      - "59095:9095"     # tempo grpc
      - "53317:4317"    # otlp grpc
      - "53318:4318"    # otlp http
  prometheus:
    image: prom/prometheus:latest
    domainname: prometheus
    ports:
      - "59590:9090"
    volumes:
      - "./conf.local/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "vol_local_prometheus:/prometheus"
  grafana:
    image: grafana/grafana:latest
    domainname: grafana
    ports:
      - "53000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: krakend
      GF_SECURITY_ADMIN_PASSWORD: krakend
      GF_AUT_ANONYMOUS_ENABLED: "true"
    volumes:
      - "vol_local_grafana:/var/lib/grafana"
      - "./conf.local/grafana/conf/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./conf.local/grafana/conf/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
      - "./conf.local/grafana/conf/data/dashboards:/var/lib/grafana/dashboards"
    depends_on:
      - prometheus
      - loki
      - tempo
  jaeger:
    image: jaegertracing/all-in-one:1.54
    domainname: jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "55778:5778"   # serve configs 
      - "56686:16686"  # serve frontend UI
      - "55317:4317"   # otlp grpc: we remap this to be able to run other envs
      - "55318:4318"   # otlp http: we reamp this to be able to run other envs
    deploy:
      resources:
        limits:
          memory: 4096M
  fakeapi:
    image: dhontecillas/reqstatsrv:latest
    domainname: fakeapi
    ports:
      - "9876:9876"
    command:
      - "./reqstatsrv"
      - "/etc/reqstatsrv/config/example.dockerized.json"
    volumes:
      - "./conf.local/fakeapi:/etc/reqstatsrv"
